# Generated by Django 4.2.6 on 2023-11-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_points_lesson_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="time_duration",
            field=models.IntegerField(null=True),
        ),
    ]
