# Generated by Django 4.2.6 on 2023-11-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_language_course_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="Certificate",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
