# Generated by Django 4.2.6 on 2023-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_course_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="Certificate",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
