# Generated by Django 4.2.6 on 2023-11-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_course_certificate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language", old_name="language", new_name="name",
        ),
    ]
