# Generated by Django 4.2.6 on 2023-11-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_rename_language_language_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language", old_name="name", new_name="language",
        ),
    ]
